local function set_hl(name, style)
  vim.api.nvim_set_hl(0, name, style)
end

local colors = {
  off_white = '#d0d0d0',
  teal = '#4a9ea0',
  soft_cyan = '#5dbfb8',
  soft_blue = '#7a9ec8',
  sage = '#7aa876',
  soft_gold = '#b8a86a',
  warm_gray = '#9a9a9a',
  muted_blue = '#6a8aae',
  base = '#18181c',
  mantle = '#1c1c21',
  surface = '#252529',
  selection = '#1a2f3a',
  selection_primary = '#2a4358',
  muted_red = '#c4666a',
  soft_yellow = '#c4a86a',
  soft_teal = '#5a9e96',
}

local function setup()
  vim.cmd('hi clear')
  vim.cmd('set termguicolors')
  vim.g.colors_name = 'sage'

  set_hl('Normal', { fg = colors.off_white, bg = colors.base })
  set_hl('NormalNC', { fg = colors.off_white, bg = colors.base })
  set_hl('Cursor', { fg = colors.base, bg = colors.teal })
  set_hl('CursorLine', { bg = colors.surface })
  set_hl('CursorLineNr', { fg = colors.off_white, bg = colors.surface, bold = true })
  set_hl('LineNr', { fg = colors.warm_gray })
  set_hl('CursorLineFold', { fg = colors.warm_gray })

  set_hl('Comment', { fg = colors.warm_gray, italic = true })
  set_hl('Constant', { fg = colors.soft_gold })
  set_hl('String', { fg = colors.sage })
  set_hl('Character', { fg = colors.sage })
  set_hl('Number', { fg = colors.soft_gold })
  set_hl('Boolean', { fg = colors.soft_gold })
  set_hl('Float', { fg = colors.soft_gold })

  set_hl('Identifier', { fg = colors.off_white })
  set_hl('Function', { fg = colors.soft_cyan, italic = true })
  set_hl('Variable', { fg = colors.off_white })
  set_hl('VariableBuiltin', { fg = colors.teal })

  set_hl('Type', { fg = colors.soft_blue, bold = true })
  set_hl('TypeBuiltin', { fg = colors.soft_blue, bold = true })
  set_hl('Struct', { fg = colors.soft_blue })
  set_hl('Enum', { fg = colors.soft_blue })
  set_hl('Class', { fg = colors.soft_blue })

  set_hl('Keyword', { fg = colors.teal })
  set_hl('KeywordFunction', { fg = colors.teal })
  set_hl('KeywordReturn', { fg = colors.teal })
  set_hl('Conditional', { fg = colors.teal })
  set_hl('Repeat', { fg = colors.teal })
  set_hl('Label', { fg = colors.teal })
  set_hl('Operator', { fg = colors.muted_blue })
  set_hl('Punctuation', { fg = colors.off_white })

  set_hl('Namespace', { fg = colors.teal, italic = true })

  set_hl('Attribute', { fg = colors.teal })

  set_hl('PreProc', { fg = colors.teal })
  set_hl('Include', { fg = colors.teal })
  set_hl('Define', { fg = colors.teal })
  set_hl('Macro', { fg = colors.teal })

  set_hl('Title', { fg = colors.teal, bold = true })
  set_hl('Macro', { fg = colors.teal })

  set_hl('Special', { fg = colors.sage })
  set_hl('SpecialChar', { fg = colors.sage })
  set_hl('Tag', { fg = colors.teal })
  set_hl('Delimiter', { fg = colors.off_white })

  set_hl('Underlined', { underline = true })
  set_hl('Ignore', {})
  set_hl('Error', { fg = colors.muted_red, bold = true, underline = true })
  set_hl('Todo', { fg = colors.soft_yellow, bold = true })
  set_hl('Warning', { fg = colors.soft_yellow })

  set_hl('Conceal', { fg = colors.warm_gray })

  set_hl('MatchParen', { bg = colors.selection_primary, bold = true })

  set_hl('Visual', { bg = colors.selection })
  set_hl('VisualNOS', { bg = colors.selection, underline = true })

  set_hl('Search', { fg = colors.base, bg = colors.soft_yellow })
  set_hl('IncSearch', { fg = colors.base, bg = colors.soft_yellow })

  set_hl('NonText', { fg = colors.warm_gray })

  set_hl('Whitespace', { fg = colors.warm_gray })

  set_hl('FoldColumn', { fg = colors.warm_gray, bg = colors.base })
  set_hl('Folded', { fg = colors.warm_gray, bg = colors.surface, italic = true })

  set_hl('StatusLine', { fg = colors.off_white, bg = colors.mantle })
  set_hl('StatusLineNC', { fg = colors.warm_gray, bg = colors.base })

  set_hl('TabLine', { fg = colors.warm_gray, bg = colors.base })
  set_hl('TabLineFill', { fg = colors.warm_gray, bg = colors.base })
  set_hl('TabLineSel', { fg = colors.off_white, bg = colors.surface, bold = true })

  set_hl('VertSplit', { fg = colors.surface, bg = colors.mantle })

  set_hl('SignColumn', { fg = colors.warm_gray, bg = colors.base })
  set_hl('SignColumnSB', { fg = colors.warm_gray, bg = colors.surface })

  set_hl('ColorColumn', { bg = colors.surface })

  set_hl('QuickFixLine', { fg = colors.soft_cyan, bold = true })

  set_hl('Debug', { fg = colors.soft_gold })
  set_hl('DebugPC', { bg = colors.surface })

  set_hl('PMenu', { fg = colors.off_white, bg = colors.surface })
  set_hl('PMenuSel', { fg = colors.base, bg = colors.teal, bold = true })
  set_hl('PMenuSbar', { bg = colors.surface })
  set_hl('PMenuThumb', { bg = colors.warm_gray })

  set_hl('Float', { bg = colors.surface })
  set_hl('NormalFloat', { fg = colors.off_white, bg = colors.surface })
  set_hl('FloatBorder', { fg = colors.off_white, bg = colors.surface })
  set_hl('FloatTitle', { fg = colors.off_white, bg = colors.surface })

  set_hl('NormalNC', { fg = colors.off_white, bg = colors.base })

  set_hl('WinBar', { fg = colors.warm_gray, bg = colors.mantle })
  set_hl('WinBarNC', { fg = colors.warm_gray, bg = colors.base })

  set_hl('diffAdded', { fg = colors.sage })
  set_hl('diffChanged', { fg = colors.soft_gold })
  set_hl('diffRemoved', { fg = colors.muted_red })
  set_hl('diffOldFile', { fg = colors.muted_red })
  set_hl('diffNewFile', { fg = colors.sage })
  set_hl('diffFile', { fg = colors.off_white })
  set_hl('diffLine', { fg = colors.teal })
  set_hl('diffIndexLine', { fg = colors.soft_gold })

  set_hl('gitSignsAdd', { fg = colors.sage })
  set_hl('gitSignsChange', { fg = colors.soft_gold })
  set_hl('gitSignsDelete', { fg = colors.muted_red })
  set_hl('GitSignsAddLn', { fg = colors.sage, bg = colors.surface })
  set_hl('GitSignsChangeLn', { fg = colors.soft_gold, bg = colors.surface })
  set_hl('GitSignsDeleteLn', { fg = colors.muted_red, bg = colors.surface })

  set_hl('DiagnosticError', { fg = colors.muted_red, bold = true, underline = true })
  set_hl('DiagnosticWarn', { fg = colors.soft_yellow, bold = true, underline = true })
  set_hl('DiagnosticInfo', { fg = colors.muted_blue, bold = true })
  set_hl('DiagnosticHint', { fg = colors.soft_teal, bold = true })

  set_hl('DiagnosticVirtualTextError', { fg = colors.muted_red, bg = colors.surface })
  set_hl('DiagnosticVirtualTextWarn', { fg = colors.soft_yellow, bg = colors.surface })
  set_hl('DiagnosticVirtualTextInfo', { fg = colors.muted_blue, bg = colors.surface })
  set_hl('DiagnosticVirtualTextHint', { fg = colors.soft_teal, bg = colors.surface })

  set_hl('DiagnosticUnderlineError', { undercurl = true, sp = colors.muted_red })
  set_hl('DiagnosticUnderlineWarn', { undercurl = true, sp = colors.soft_yellow })
  set_hl('DiagnosticUnderlineInfo', { undercurl = true, sp = colors.muted_blue })
  set_hl('DiagnosticUnderlineHint', { undercurl = true, sp = colors.soft_teal })

  set_hl('DiagnosticFloatingError', { fg = colors.muted_red, bg = colors.surface })
  set_hl('DiagnosticFloatingWarn', { fg = colors.soft_yellow, bg = colors.surface })
  set_hl('DiagnosticFloatingInfo', { fg = colors.muted_blue, bg = colors.surface })
  set_hl('DiagnosticFloatingHint', { fg = colors.soft_teal, bg = colors.surface })

  set_hl('LspReferenceText', { fg = colors.teal, underline = true })
  set_hl('LspReferenceRead', { fg = colors.teal, underline = true })
  set_hl('LspReferenceWrite', { fg = colors.teal, underline = true })

  set_hl('LspCodeLens', { fg = colors.warm_gray })
  set_hl('LspCodeLensLine', { bg = colors.surface })
  set_hl('LspSignatureActiveParameter', { fg = colors.teal, bg = colors.surface })

  set_hl('TSKeyword', { fg = colors.teal })
  set_hl('TSKeywordFunction', { fg = colors.teal })
  set_hl('TSKeywordReturn', { fg = colors.teal })
  set_hl('TSConstant', { fg = colors.soft_gold })
  set_hl('TSString', { fg = colors.sage })
  set_hl('TSCharacter', { fg = colors.sage })
  set_hl('TSNumber', { fg = colors.soft_gold })
  set_hl('TSBoolean', { fg = colors.soft_gold })
  set_hl('TSFloat', { fg = colors.soft_gold })

  set_hl('TSVariable', { fg = colors.off_white })
  set_hl('TSVariableBuiltin', { fg = colors.teal })
  set_hl('TSFunction', { fg = colors.soft_cyan, italic = true })
  set_hl('TSMethod', { fg = colors.soft_cyan, italic = true })

  set_hl('TSType', { fg = colors.soft_blue, bold = true })
  set_hl('TSTypeBuiltin', { fg = colors.soft_blue, bold = true })
  set_hl('TSStruct', { fg = colors.soft_blue })
  set_hl('TSEnum', { fg = colors.soft_blue })
  set_hl('TSClass', { fg = colors.soft_blue })

  set_hl('TSNamespace', { fg = colors.teal, italic = true })

  set_hl('TSProperty', { fg = colors.off_white })
  set_hl('TSField', { fg = colors.off_white })
  set_hl('TSParameter', { fg = colors.off_white, italic = true })
  set_hl('TSParameterBuiltin', { fg = colors.teal, italic = true })

  set_hl('TSOperator', { fg = colors.muted_blue })
  set_hl('TSpunctuation', { fg = colors.off_white })

  set_hl('TSAttribute', { fg = colors.teal })

  set_hl('TSComment', { fg = colors.warm_gray, italic = true })
  set_hl('TSNote', { fg = colors.soft_teal })
  set_hl('TSWarning', { fg = colors.soft_yellow })
  set_hl('TSDanger', { fg = colors.muted_red })

  set_hl('TSText', { fg = colors.off_white })
  set_hl('TSEmphasis', { fg = colors.off_white, italic = true })
  set_hl('TSStrong', { fg = colors.off_white, bold = true })
  set_hl('TSStringSpecial', { fg = colors.sage })
  set_hl('TSLiteral', { fg = colors.sage })

  set_hl('TSUri', { fg = colors.soft_cyan, underline = true })

  set_hl('TSTitle', { fg = colors.teal, bold = true })
  set_hl('TSLabel', { fg = colors.teal })
  set_hl('TSHeading', { fg = colors.teal, bold = true })

  set_hl('TreesitterContext', { bg = colors.surface })
  set_hl('TreesitterContextLineNumber', { fg = colors.teal, bg = colors.surface })

  set_hl('@lsp.type.class', { fg = colors.soft_blue })
  set_hl('@lsp.type.struct', { fg = colors.soft_blue })
  set_hl('@lsp.type.enum', { fg = colors.soft_blue })
  set_hl('@lsp.type.interface', { fg = colors.soft_blue })
  set_hl('@lsp.type.type', { fg = colors.soft_blue })
  set_hl('@lsp.type.typeParameter', { fg = colors.soft_blue })
  set_hl('@lsp.type.function', { fg = colors.soft_cyan })
  set_hl('@lsp.type.method', { fg = colors.soft_cyan })
  set_hl('@lsp.type.property', { fg = colors.off_white })
  set_hl('@lsp.type.variable', { fg = colors.off_white, bold = true })
  set_hl('@lsp.type.parameter', { fg = colors.off_white, italic = true })
  set_hl('@lsp.type.constant', { fg = colors.soft_gold })
  set_hl('@lsp.type.enumMember', { fg = colors.soft_gold })
  set_hl('@lsp.type.namespace', { fg = colors.teal, italic = true })
  set_hl('@lsp.type.keyword', { fg = colors.teal })
  set_hl('@lsp.type.operator', { fg = colors.muted_blue })
  set_hl('@lsp.type.string', { fg = colors.sage })
  set_hl('@lsp.type.number', { fg = colors.soft_gold })
  set_hl('@lsp.type.boolean', { fg = colors.soft_gold })

  set_hl('@comment', { fg = colors.warm_gray, italic = true })
  set_hl('@attribute', { fg = colors.teal })
  set_hl('@type', { fg = colors.soft_blue, bold = true })
  set_hl('@type.builtin', { fg = colors.soft_blue, bold = true })
  set_hl('@constructor', { fg = colors.soft_blue })
  set_hl('@constant', { fg = colors.soft_gold })
  set_hl('@constant.builtin', { fg = colors.soft_gold })
  set_hl('@string', { fg = colors.sage })
  set_hl('@variable', { fg = colors.off_white })
  set_hl('@variable.parameter', { fg = colors.off_white, italic = true })
  set_hl('@variable.builtin', { fg = colors.teal })
  set_hl('@keyword', { fg = colors.teal })
  set_hl('@keyword.function', { fg = colors.teal })
  set_hl('@keyword.operator', { fg = colors.teal })
  set_hl('@operator', { fg = colors.muted_blue })
  set_hl('@function', { fg = colors.soft_cyan, italic = true })
  set_hl('@function.builtin', { fg = colors.soft_cyan })
  set_hl('@function.method', { fg = colors.soft_cyan, italic = true })
  set_hl('@namespace', { fg = colors.teal, italic = true })
  set_hl('@markup.heading', { fg = colors.teal, bold = true })
  set_hl('@markup.heading.1', { fg = colors.teal, bold = true })
  set_hl('@markup.heading.2', { fg = colors.teal, bold = true })
  set_hl('@markup.heading.3', { fg = colors.teal, bold = true })
  set_hl('@markup.heading.4', { fg = colors.teal, bold = true })
  set_hl('@markup.bold', { fg = colors.off_white, bold = true })
  set_hl('@markup.italic', { fg = colors.off_white, italic = true })
  set_hl('@markup.underline', { fg = colors.off_white, underline = true })
  set_hl('@markup.strikethrough', { fg = colors.warm_gray, strikethrough = true })
  set_hl('@markup.link', { fg = colors.soft_cyan, underline = true })
  set_hl('@markup.raw', { fg = colors.sage })

  set_hl('@tag', { fg = colors.teal })
  set_hl('@tag.attribute', { fg = colors.soft_gold })
  set_hl('@tag.delimiter', { fg = colors.warm_gray })

  set_hl('@punctuation', { fg = colors.off_white })
  set_hl('@punctuation.bracket', { fg = colors.off_white })
  set_hl('@punctuation.delimiter', { fg = colors.off_white })
  set_hl('@punctuation.special', { fg = colors.off_white })

  set_hl('FlashLabel', { bg = colors.selection_primary, fg = colors.base, bold = true })
  set_hl('FlashMatch', { bg = colors.selection, fg = colors.base, bold = true })
  set_hl('FlashCurrent', { bg = colors.selection, fg = colors.base })

  set_hl('MiniTablineHidden', { fg = colors.warm_gray, bg = colors.base })
  set_hl('MiniTablineActive', { fg = colors.off_white, bg = colors.surface, bold = true })
  set_hl('MiniTablineVisible', { fg = colors.off_white, bg = colors.base })
  set_hl('MiniTablineSelectedActive', { fg = colors.off_white, bg = colors.surface, bold = true })
  set_hl('MiniTablineSelectedVisible', { fg = colors.off_white, bg = colors.surface, bold = true })

  set_hl('BlinkCmpMenu', { fg = colors.off_white, bg = colors.surface })
  set_hl('BlinkCmpMenuBorder', { fg = colors.surface, bg = colors.surface })
  set_hl('BlinkCmpMenuSelection', { fg = colors.base, bg = colors.teal, bold = true })
  set_hl('BlinkCmpMenuBackdrop', { bg = colors.surface })
  set_hl('BlinkCmpDoc', { fg = colors.off_white, bg = colors.surface })
  set_hl('BlinkCmpDocBorder', { fg = colors.surface, bg = colors.surface })
  set_hl('BlinkCmpDocSelection', { fg = colors.base, bg = colors.teal, bold = true })
  set_hl('BlinkCmpDocBackdrop', { bg = colors.surface })

  set_hl('BlinkCmpLabel', { fg = colors.off_white })
  set_hl('BlinkCmpLabelMatch', { fg = colors.teal, bold = true })
  set_hl('BlinkCmpLabelDeprecated', { fg = colors.warm_gray, strikethrough = true })
  set_hl('BlinkCmpLabelDescription', { fg = colors.warm_gray })
  set_hl('BlinkCmpKind', { fg = colors.teal })
  set_hl('BlinkCmpKindMatch', { fg = colors.soft_cyan })
  set_hl('BlinkCmpKindText', { fg = colors.off_white })
  set_hl('BlinkCmpKindMethod', { fg = colors.soft_cyan })
  set_hl('BlinkCmpKindFunction', { fg = colors.soft_cyan })
  set_hl('BlinkCmpKindConstructor', { fg = colors.soft_blue })
  set_hl('BlinkCmpKindVariable', { fg = colors.off_white })
  set_hl('BlinkCmpKindClass', { fg = colors.soft_blue })
  set_hl('BlinkCmpKindInterface', { fg = colors.soft_blue })
  set_hl('BlinkCmpKindStruct', { fg = colors.soft_blue })
  set_hl('BlinkCmpKindEnum', { fg = colors.soft_blue })
  set_hl('BlinkCmpKindEnumMember', { fg = colors.soft_gold })
  set_hl('BlinkCmpKindProperty', { fg = colors.off_white })
  set_hl('BlinkCmpKindField', { fg = colors.off_white })
  set_hl('BlinkCmpKindConstant', { fg = colors.soft_gold })
  set_hl('BlinkCmpKindSnippet', { fg = colors.sage })
  set_hl('BlinkCmpKindModule', { fg = colors.teal })
  set_hl('BlinkCmpKindFile', { fg = colors.sage })
  set_hl('BlinkCmpKindFolder', { fg = colors.warm_gray })
  set_hl('BlinkCmpKindUnit', { fg = colors.soft_cyan })
  set_hl('BlinkCmpKindReference', { fg = colors.warm_gray })
  set_hl('BlinkCmpKindKeyword', { fg = colors.teal })
  set_hl('BlinkCmpKindOperator', { fg = colors.muted_blue })
  set_hl('BlinkCmpKindTypeParameter', { fg = colors.soft_blue })

  set_hl('TelescopeBorder', { fg = colors.surface, bg = colors.base })
  set_hl('TelescopeTitle', { fg = colors.teal })
  set_hl('TelescopeSelection', { link = 'CursorLine' })
  set_hl('TelescopeSelectionCaret', { link = 'CursorLineNr' })
  set_hl('TelescopeResultsClass', { link = 'Structure' })
  set_hl('TelescopeResultsStruct', { link = 'Structure' })
  set_hl('TelescopeResultsField', { fg = colors.off_white })
  set_hl('TelescopeResultsMethod', { link = 'Function' })
  set_hl('TelescopeResultsVariable', { fg = colors.off_white })

  set_hl('SupermavenNormal', { fg = colors.off_white, bg = colors.base })
  set_hl('SupermavenSelection', { fg = colors.off_white, bg = colors.surface })
  set_hl('SupermavenBorder', { fg = colors.surface, bg = colors.base })

  set_hl('LualineNormal', { fg = colors.off_white, bg = colors.mantle })
  set_hl('LualineInsert', { fg = colors.base, bg = colors.sage, bold = true })
  set_hl('LualineVisual', { fg = colors.base, bg = colors.teal, bold = true })
  set_hl('LualineCommand', { fg = colors.base, bg = colors.soft_gold, bold = true })
  set_hl('LualineReplace', { fg = colors.base, bg = colors.muted_red, bold = true })
  set_hl('LualineTerminal', { fg = colors.base, bg = colors.soft_cyan, bold = true })
  set_hl('LualineInactive', { fg = colors.warm_gray, bg = colors.base })

  set_hl('DiffviewNormal', { bg = colors.surface })
  set_hl('DiffviewFilePanelTitle', { fg = colors.teal, bold = true })
  set_hl('DiffviewFilePanelFileName', { fg = colors.off_white })
  set_hl('DiffviewFilePanelPath', { fg = colors.warm_gray })
  set_hl('DiffviewFilePanelSelection', { bg = colors.selection })
  set_hl('DiffviewHistoryPanelTitle', { fg = colors.teal, bold = true })
  set_hl('DiffviewHistoryPanelFile', { fg = colors.off_white })
  set_hl('DiffviewPanelTitle', { fg = colors.teal, bold = true })
  set_hl('DiffViewPanelFile', { fg = colors.off_white })
  set_hl('DiffviewStatusModified', { fg = colors.sage })
  set_hl('DiffviewStatusAdded', { fg = colors.sage })
  set_hl('DiffviewStatusRenamed', { fg = colors.sage })
  set_hl('DiffviewStatusDeleted', { fg = colors.muted_red })
  set_hl('DiffviewStatusUnknown', { fg = colors.warm_gray })

  set_hl('MiniIconsDirectory', { fg = colors.warm_gray })
  set_hl('MiniIconsFile', { fg = colors.off_white })
  set_hl('MiniIconsSymlinkFile', { fg = colors.soft_cyan })
  set_hl('MiniIconsLua', { fg = colors.soft_cyan })
  set_hl('MiniIconsJson', { fg = colors.soft_yellow })
  set_hl('MiniIconsJs', { fg = colors.sage })
  set_hl('MiniIconsTs', { fg = colors.soft_cyan })
  set_hl('MiniIconsMd', { fg = colors.soft_blue })

  set_hl('Exception', { fg = colors.muted_red })
  set_hl('PreCondit', { fg = colors.teal })
  set_hl('StorageClass', { fg = colors.soft_blue })
  set_hl('Structure', { fg = colors.soft_blue })
  set_hl('Typedef', { fg = colors.soft_blue })
  set_hl('SpecialChar', { fg = colors.sage })
  set_hl('Debug', { fg = colors.soft_gold })
  set_hl('MoreMsg', { fg = colors.muted_blue })
  set_hl('Question', { fg = colors.muted_blue })
  set_hl('ModeMsg', { fg = colors.soft_yellow, bold = true })
  set_hl('MsgArea', { fg = colors.warm_gray })
  set_hl('MsgSeparator', { fg = colors.surface, bg = colors.mantle })
  set_hl('WarningMsg', { fg = colors.soft_yellow })
  set_hl('ErrorMsg', { fg = colors.muted_red })

  set_hl('CurSearch', { fg = colors.base, bg = colors.soft_yellow, bold = true })
  set_hl('Substitute', { fg = colors.base, bg = colors.muted_red })
  set_hl('SpellBad', { undercurl = true, sp = colors.muted_red })
  set_hl('SpellCap', { undercurl = true, sp = colors.soft_yellow })
  set_hl('SpellLocal', { undercurl = true, sp = colors.soft_yellow })
  set_hl('SpellRare', { undercurl = true, sp = colors.soft_teal })

  set_hl('Directory', { fg = colors.soft_cyan })
  set_hl('EndOfBuffer', { fg = colors.base })
  set_hl('SpecialKey', { fg = colors.warm_gray })

  set_hl('WildMenu', { link = 'Pmenu' })

  set_hl('Bold', { bold = true })
  set_hl('Italic', { italic = true })

  set_hl('qfLineNr', { fg = colors.warm_gray })
  set_hl('qfFileName', { link = 'Directory' })

  set_hl('markdownCode', { fg = colors.sage })
  set_hl('markdownCodeBlock', { fg = colors.sage })

  set_hl('@variable.member', { fg = colors.off_white })
  set_hl('@module', { fg = colors.teal, italic = true })
  set_hl('@module.builtin', { fg = colors.teal })
  set_hl('@label', { fg = colors.teal })
  set_hl('@string.regexp', { fg = colors.soft_gold })
  set_hl('@string.escape', { fg = colors.soft_gold, bold = true })
  set_hl('@string.special.symbol', { fg = colors.off_white })
  set_hl('@string.special.url', { fg = colors.soft_cyan, underline = true })
  set_hl('@type.definition', { fg = colors.soft_blue })
  set_hl('@property', { fg = colors.off_white })
  set_hl('@function.call', { fg = colors.soft_cyan, italic = true })
  set_hl('@function.macro', { fg = colors.teal })
  set_hl('@keyword.return', { fg = colors.teal })
  set_hl('@keyword.exception', { fg = colors.muted_red, bold = true })
  set_hl('@keyword.import', { fg = colors.teal })
  set_hl('@keyword.conditional', { fg = colors.teal })
  set_hl('@keyword.repeat', { fg = colors.teal })
  set_hl('@comment.error', { fg = colors.base, bg = colors.muted_red, bold = true })
  set_hl('@comment.warning', { fg = colors.base, bg = colors.soft_yellow, bold = true })
  set_hl('@comment.note', { fg = colors.base, bg = colors.soft_teal, bold = true })
  set_hl('@markup.quote', { fg = colors.warm_gray, italic = true })
  set_hl('@markup.math', { fg = colors.soft_gold })
  set_hl('@markup.environment', { fg = colors.teal })
  set_hl('@markup.link.label', { fg = colors.soft_cyan })
  set_hl('@markup.link.url', { fg = colors.soft_cyan, underline = true })
  set_hl('@markup.list', { fg = colors.warm_gray })
  set_hl('@markup.list.checked', { fg = colors.sage })
  set_hl('@markup.list.unchecked', { fg = colors.warm_gray })
  set_hl('@diff.plus', { fg = colors.sage })
  set_hl('@diff.minus', { fg = colors.muted_red })
  set_hl('@diff.delta', { fg = colors.soft_gold })
  set_hl('@tag.builtin', { fg = colors.teal })

  set_hl('@lsp.type.macro', { fg = colors.teal })
  set_hl('@lsp.type.selfParameter', { fg = colors.teal, italic = true })
  set_hl('@lsp.type.builtinConstant', { fg = colors.soft_gold })
  set_hl('@lsp.type.magicFunction', { fg = colors.soft_cyan })
  set_hl('@lsp.mod.readonly', { fg = colors.soft_gold, bold = true })
  set_hl('@lsp.mod.typeHint', { fg = colors.soft_blue })
  set_hl('@lsp.typemod.variable.global', { fg = colors.soft_gold })
  set_hl('@lsp.typemod.variable.static', { fg = colors.soft_gold })
  set_hl('@lsp.typemod.variable.defaultLibrary', { fg = colors.teal })
  set_hl('@lsp.typemod.function.builtin', { fg = colors.soft_cyan })
  set_hl('@lsp.typemod.function.defaultLibrary', { fg = colors.soft_cyan })
  set_hl('@lsp.typemod.method.defaultLibrary', { fg = colors.soft_cyan })
  set_hl('@lsp.typemod.variable.injected', { fg = colors.sage })
  set_hl('@lsp.typemod.function.readonly', { fg = colors.soft_cyan, bold = true })

  set_hl('IndentBlanklineChar', { fg = colors.surface })
  set_hl('IndentBlanklineSpaceChar', { fg = colors.surface })
  set_hl('IndentBlanklineContextChar', { fg = colors.teal })
  set_hl('IblIndent', { fg = colors.surface })
  set_hl('IblWhitespace', { fg = colors.surface })
  set_hl('IblScope', { fg = colors.teal })

  set_hl('DiagnosticOk', { fg = colors.sage })

  set_hl('NeogitDiffContextHighlight', { bg = colors.surface })
  set_hl('NeogitHunkHeader', { fg = colors.off_white })
  set_hl('NeogitHunkHeaderHighlight', { fg = colors.soft_gold, bg = colors.surface })
  set_hl('NeogitDiffAddHighlight', { bg = colors.surface })
  set_hl('NeogitDiffDeleteHighlight', { bg = colors.surface })

  set_hl('NvimTreeNormal', { fg = colors.off_white, bg = colors.base })
  set_hl('NvimTreeNormalNC', { fg = colors.off_white, bg = colors.base })
  set_hl('NvimTreeRootFolder', { fg = colors.off_white, bold = true })
  set_hl('NvimTreeGitDirty', { fg = colors.soft_gold })
  set_hl('NvimTreeGitNew', { fg = colors.sage })
  set_hl('NvimTreeGitDeleted', { fg = colors.muted_red })
  set_hl('NvimTreeGitStaged', { fg = colors.sage })
  set_hl('NvimTreeSpecialFile', { fg = colors.sage })
  set_hl('NvimTreeImageFile', { fg = colors.muted_red })
  set_hl('NvimTreeSymlink', { fg = colors.soft_blue })
  set_hl('NvimTreeFolderName', { link = 'Directory' })
  set_hl('NvimTreeExecFile', { fg = colors.sage, bold = true })
  set_hl('NvimTreeOpenedFile', { fg = colors.sage, italic = true })
  set_hl('NvimTreeWinSeparator', { link = 'VertSplit' })
  set_hl('NvimTreeWindowPicker', { bg = colors.surface, fg = colors.teal, bold = true })

  set_hl('NeoTreeTabInactive', { link = 'TabLine' })
  set_hl('NeoTreeTabActive', { link = 'TabLineSel' })
  set_hl('NeoTreeTabSeparatorInactive', { link = 'TabLine' })
  set_hl('NeoTreeTabSeparatorActive', { link = 'TabLineSel' })
  set_hl('NeoTreeRootName', { fg = colors.off_white, bold = true })
  set_hl('NeoTreeModified', { fg = colors.sage })
  set_hl('NeoTreeGitModified', { fg = colors.soft_gold })
  set_hl('NeoTreeGitAdded', { fg = colors.sage })
  set_hl('NeoTreeGitDeleted', { fg = colors.muted_red })
  set_hl('NeoTreeGitStaged', { fg = colors.sage })
  set_hl('NeoTreeGitConflict', { fg = colors.muted_red })
  set_hl('NeoTreeIndentMarker', { link = 'NonText' })

  set_hl('MiniFilesBorder', { link = 'FloatBorder' })
  set_hl('MiniFilesBorderModified', { link = 'DiagnosticWarn' })
  set_hl('MiniFilesCursorLine', { link = 'CursorLine' })
  set_hl('MiniFilesDirectory', { link = 'Directory' })
  set_hl('MiniFilesFile', { fg = colors.off_white })
  set_hl('MiniFilesNormal', { link = 'NormalFloat' })
  set_hl('MiniFilesTitle', { fg = colors.teal, bg = colors.surface, bold = true })
end

setup()

return { colors = colors, setup = setup }
